---
version: '3'
services:
  quine:
    image: timberio/vector:0.21.2-distroless-libc
    container_name: vector
    environment:
      -  VECTOR_CONFIG_TOML=/vector.toml
    restart: always
    volumes:
      - ./vector.toml:/vector.toml
      - /var/log:/var/log
      - /usr/local/red5pro/log:/usr/local/red5pro/log
